import { TARGET_PROFILES, TargetProfile } from './target_profiles';
import { RUNEHALL_AFFILIATES, RUNEHALL_USER_MAP } from './runehall_intel';

export interface Dossier {
  target: string;
  timestamp: string;
  profile: TargetProfile;
  forumActivity: {
    platform: string;
    username: string;
    status: string;
    notes: string;
  }[];
  gamingHistory: {
    game: string;
    activity: string;
    level: string;
  }[];
  networkFootprint: {
    ip: string;
    role: string;
    location: string;
  }[];
}

export function generateDossier(targetName: string): Dossier | null {
  const profile = TARGET_PROFILES[targetName];
  if (!profile) return null;

  // Mocking some additional data based on the target profile and general intel
  const forumActivity = [
    { 
      platform: "Sythe.org", 
      username: profile.socials["Sythe"] || targetName, 
      status: "Active / Moderator", 
      notes: "Linked to multiple high-value GP trades. Previous scam reports under 'S_G_Rune' archived." 
    },
    { 
      platform: "HackForums", 
      username: profile.variants[0] || targetName, 
      status: "Elite Member", 
      notes: "Active in the 'Currency Exchange' and 'Botting' sections." 
    }
  ];

  const gamingHistory = [
    { 
      game: "Old School RuneScape", 
      activity: "High-stakes staking / GP Swapping", 
      level: "Combat 126 / Total 2277" 
    },
    { 
      game: "Runehall (Casino)", 
      activity: "Admin / High-Roller", 
      level: "Tier 5 VIP" 
    }
  ];

  const networkFootprint = profile.ipAddresses.map(ip => {
    let role = "Proxy / VPN";
    let location = "Unknown";

    if (ip === "172.67.132.44") {
      role = "Cloudflare Edge Proxy";
      location = "San Francisco, CA";
    } else if (ip === "108.95.121.60") {
      role = "Residential Ingress (AT&T)";
      location = "San Diego, CA";
    } else if (ip === "151.0.214.242") {
      role = "Regional API Ingress";
      location = "San Francisco, CA";
    } else if (ip === "45.33.22.11") {
      role = "Linode VPS (C2 Node)";
      location = "Dallas, TX";
    }

    return { ip, role, location };
  });

  return {
    target: targetName,
    timestamp: new Date().toISOString(),
    profile,
    forumActivity,
    gamingHistory,
    networkFootprint
  };
}

export function dossierToMarkdown(dossier: Dossier): string {
  return `
# TARGET DOSSIER: ${dossier.target}
**Generated:** ${new Date(dossier.timestamp).toLocaleString()}
**Classification:** TOP SECRET // AEGIS-ULTIMA

## 1. IDENTITY & VARIANTS
- **Primary Name:** ${dossier.profile.name}
- **Known Aliases:** ${dossier.profile.variants.join(', ')}
- **Emails:** ${dossier.profile.emails.join(', ')}
- **Phone Numbers:** ${dossier.profile.phoneNumbers.join(', ')}

## 2. SOCIAL MEDIA & FORUMS
${dossier.forumActivity.map(f => `- **${f.platform}:** ${f.username} (${f.status}) - ${f.notes}`).join('\n')}
${Object.entries(dossier.profile.socials).map(([p, u]) => `- **${p}:** ${u}`).join('\n')}

## 3. GAMING HISTORY
${dossier.gamingHistory.map(g => `- **${g.game}:** ${g.activity} (Level/Rank: ${g.level})`).join('\n')}

## 4. NETWORK FOOTPRINT
${dossier.networkFootprint.map(n => `- **${n.ip}:** ${n.role} [${n.location}]`).join('\n')}

## 5. OPERATIONAL NOTES
${dossier.profile.notes}

---
*Generated by Aegis OSINT Intelligence Module*
  `;
}
